### ISSUE TITLE
Would it be possible to add benchmarking code

### ISSUE THREAD

**Issue by MichaelWyrley** [hynann/NRDF#2]
Hi there,

I was wondering if it would be possible for you to add the code you used to benchmark the system to the repo, specifically for diverse pose generation.
I am trying to make a similar system using Riemanian flow matching and would like to compare the generation results for mine verses the papers.

**Comment by hynann** [comment]
Hi, thank you for your interest in our work! You can check lib/exp/sample_poses.py to reproduce the diverse pose generation results. We have also added the way to calculate metrics in our latest version.
