### ISSUE TITLE
KeyError because of --occ-type parameter

### ISSUE THREAD

**Issue by MelihDarcanxyz** [hynann/NRDF#6]
Hi, first of all, thanks for making this great work open source.

While trying to get partial IK work, I got an error. The code doesn't work with `--occ_type all` despite it's intended to work in the source code.

`all` key is present in [partial_joint_index](https://github.com/hynann/NRDF/blob/d9342f07a9941bde8da67babb1c99811f3abf7a7/lib/utils/exp_utils.py#L29) dict. However, it's not present in [body_parts](https://github.com/hynann/NRDF/blob/d9342f07a9941bde8da67babb1c99811f3abf7a7/lib/utils/exp_utils.py#L20) dict. [get_marker_vids](https://github.com/hynann/NRDF/blob/d9342f07a9941bde8da67babb1c99811f3abf7a7/lib/utils/exp_utils.py#L38) function tries to access the `--occ_type` key of these dictionaries, which in this case `all`. So we get `KeyError`.

I'm not really sure about the intended behavior about these dictionaries, so wanted to open an issue. Have a nice day!

**Comment by hynann** [comment]
Hi Melih, thanks for you interest in our work! Indeed the 'all' key was missing in body_parts dict, now it should be fixed:)

Thanks again for pointing out the issue.
